---
title: "Pre-course self reflection (SR #1)"
author: "Peter Vitale"
date: 2026-01-09
---

::: {.callout-note}
*For the full assignment description and grading specifications, please see the course website: <https://eds-240-data-viz.github.io/course-materials/assignments/SR1-precourse.html>*
:::

## Outline your learning goals & plan: 

  - [ ] **1. Which learning goals from the syllabus are you most excited about?** 

 I am excited to build pretty plots, which also are effective and responsible. 

  - [ ] **2. What do you hope to get out of this class?**

I really like visualizing in R, and am excited to continue to develop and hone my skills. 

  - [ ] **3. How do you plan on accomplishing your learning goals for this course? *Note:* be specific here! Instead of writing, “I will complete homework assignments” or “I will study,” you can make these more specific strategies: “I will create a schedule to map out assignments“ (elaborate on this), “I will use the homework assignments as opportunities to practice X,” I will communicate with classmates to ask for help after trying X,” “I will participate in online learning communities, such as TidyTuesday...” etc.**

This quarter especially, proper calendar management will be essential, which is why I am trying to up my game in google calendar. I have already implemented multiple tips and tricks I have seen online and am always on the lookout for how to make planning easier. 

## (Optional) Help me get to know you better!

  - [ ] **1. Where are you coming from (e.g. “I recently finished my undergraduate degree”, “I've been working in industry X for Y years”)?** 

   I have been working in education for 2 years following my graduation from UC Santa Cruz.

  - [ ] **2. If you have a particular career goal in mind, how does this course apply to your future career, if at all?**

    I would like to continue to visualize data in the future and want to become a master, so this course fits directly with those goals. 

  - [ ] **3. What do you wish your instructors knew about you, but don't?**

    Nothing! I'm a pretty open book. 

  - [ ] **4. What kinds of assignments, skills, or behaviors have you felt most comfortable with / enjoy from past classes? Why do you enjoy them?**

    I really like the more open ended assignments where I can be creative. 

  - [ ] **5. How confident do you feel in your data visualization skills? Why?**

 I would say I'm at a solid 6. I'm familiar and I take things like colorblind friendly color palettes into mind, but I do still hit a point where I know it could look better but I don't know how. 

  - [ ] **6. How confident do you feel in your coding skills (primarily R, but feel free to elaborate on any of the languages you’ve used)? Why?** 

    I feel like im at a 7, mostly due to my confidence with R and understanding the documentation. 

  - [ ] **7. What have you struggled with in the past in other graduate-level courses? Why?**

    I have struggled with being overwhelmed, and will be working on calming myself down with routines such as crochet. 

  - [ ] **8. Of the courses you’re taking this quarter, which do you expect to be the most challenging? Most demanding?**

    I expect the capstone to take up a majority of my time and be the most challenging, due to the fact that it is largely without supervision meaning we will need to get all the answers for ourselves. 

  - [ ] **9. What responsibilities do you have outside of school, and how do you want to balance them?**

    I have no other obligations. 

  - [ ] **10. What activity(ies) (outside of school / work) brings you the most joy? How do you plan to incorporate that activity into your schedule this quarter (if at all)? If you are unable to do so, is there something else you can plan to do that will bring you similar joy?** 

    I will continue to crochet, as well as try to play soccer 2x per week.  

  - [ ] **11. What is a piece of media you enjoyed recently (e.g. music, book, movie, meme)?** 
  
   Wake Up Dead Man: A Knives Out Mystery